---
zuul:
  routes:
    demo:
      path: /demo/**
      url: http://localhost:8000/

# Demo specific - not related to Zuul
error--throw-filter:
  enabled: false

pre-filter:
  enabled: false

post-filter:
  enabled: false

route-filter:
  enabled: false

routing-percentage: 0.2f
