---
zuul:
  routes:
    demo:
      path: /demo/**
      url: http://localhost:8000/

pre-filter:
  enabled: true

post-filter:
  enabled: false

route-filter:
  enabled: false

routing-percentage: 0.2f
