---
zuul:
  routes:
    demo:
      path: /demo/**
      url: http://localhost:8000/

pre-filter:
  enabled: true

post-filter:
  enabled: true

route-filter:
  enabled: true

routing-percentage: 0.2f
