---
zuul:
  ignored-patterns: /the/path/to/listen/to/ignored/**
  routes:
    path: # This can be named whatever makes sense to you
      path: /the/path/to/listen/to/*
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      url: https://google.com
#      url: ${wiremock.host}/the/path/to/proxy/to

wiremock:
  host: localhost:8181

api:
  token: token-value

response:
  header-name: X-Request-Id

pre-filter:
  enabled: true

post-filter:
  enabled: false

route-filter:
  enabled: false
